// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/awisu2/gin-study/tryFunctions/frameworks/gin"
	gin3 "github.com/awisu2/gin-study/tryFunctions/notes/adapters/gin"
	"github.com/awisu2/gin-study/tryFunctions/notes/repositories"
	usecase2 "github.com/awisu2/gin-study/tryFunctions/notes/usecases"
	gin2 "github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func InitializeFrameworkGin(opts *gin.FrameworkGinOptions) *gin.FrameworkGin {
	frameworkGin := gin.ProvideFrameworkGin(opts)
	return frameworkGin
}

func InitializeNotesGinAdapter(e *gin2.Engine, datas usecase.MemoryNotes) *gin3.NotesGinAdapter {
	notesMemoryRepository := usecase.ProvideNotesRepository(datas)
	notesUsecase := usecase2.ProvideNoteUsecase(notesMemoryRepository)
	notesGinAdapter := gin3.ProvideNotesGinAdapter(e, notesUsecase)
	return notesGinAdapter
}
